const EQUIP_ITEM_IMAGES: Record<string, any> = {
  brasao_coragem:   require('../assets/images/brasao_coragem.webp'),
  brasao_esperanca: require('../assets/images/brasao_esperanca_v4.webp'),
  brasao_amizade:   require('../assets/images/brasao_amizade.webp'),
  brasao_confianca: require('../assets/images/brasao_confianca.webp'),
  brasao_pureza:    require('../assets/images/brasao_pureza.webp'),
  brasao_amor:      require('../assets/images/brasao_amor.webp'),
  brasao_luz:           require('../assets/images/brasao_luz.webp'),
  digivice_d2:             require('../assets/images/digivice_d2.webp'),
  digivice_d3:             require('../assets/images/digivice_d3.webp'),
  oculos_escuro_fitado:    require('../assets/images/oculos_escuro_fitado.webp'),
  brasao_conhecimento:  require('../assets/images/brasao_conhecimento.webp'),
  pulseira_ouro:        require('../assets/images/pulseira_ouro.webp'),
  anel_sagrado:         require('../assets/images/anel_sagrado.webp'),
  piece_anel_sagrado:   require('../assets/images/anel_sagrado.webp'),
  piece_agulha:         require('../assets/images/agulha-media.webp'),
  piece_tecido:         require('../assets/images/tecido-arco-iris.webp'),
  piece_linha:          require('../assets/images/linha-arco-iris.webp'),
  piece_coragem:        require('../assets/images/brasao-coragem.webp'),
  piece_battery_green:  require('../assets/images/battery_green.webp'),
  piece_battery_blue:   require('../assets/images/battery_blue.webp'),
  piece_battery_purple: require('../assets/images/battery_purple.webp'),
  piece_battery_gold:   require('../assets/images/battery_gold.webp'),
  blusa_social:     require('../assets/images/blusa_social.webp'),
  bermuda_poliester: require('../assets/images/bermuda_poliester.webp'),
  tenis_corrida:    require('../assets/images/tenis_corrida.webp'),
  gehenna:              require('../assets/images/gehenna.webp'),
  piece_gehenna:        require('../assets/images/gehenna.webp'),
  permissao_real:       require('../assets/images/permissao_real.webp'),
  black_digitron:       require('../assets/images/items/black_digitron.webp'),
  piece_black_digitron: require('../assets/images/items/black_digitron.webp'),
  x_antibody:           require('../assets/images/items/x_antibody.webp'),
  piece_x_antibody:     require('../assets/images/items/x_antibody.webp'),
};

export default EQUIP_ITEM_IMAGES;
